logging:
  level: INFO
  loggers:
    "com.rk": DEBUG
    "org.apache.activemq": INFO
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
    "org.hibernate.engine.internal.StatisticalLoggingSessionEventListener": WARN
  appenders:
    - type: console
      threshold: INFO
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m [%t]%n%rEx"
    - type: file
      currentLogFilename: ./app.log
      archivedLogFilenamePattern: ./app-%d.log.gz
      archivedFileCount: 7
      threshold: INFO
      timeZone: "UTC"
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m [%t]%n%rEx"
